# Generated by Django 4.0.1 on 2022-03-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='phone_number',
            new_name='phone_extension',
        ),
        migrations.AlterField(
            model_name='employee',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='room_id', on_delete=django.db.models.deletion.CASCADE, to='api.room'),
        ),
    ]
