# Generated by Django 4.0.3 on 2022-04-18 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_phone_number_room_phone_extension_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Title',
            fields=[
                ('title_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='room_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title_after',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='title_before',
        ),
        migrations.AddField(
            model_name='employee',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='suffix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='EmployeeTitle',
            fields=[
                ('employee_title_id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.IntegerField()),
                ('location', models.CharField(choices=[('before', 'before'), ('after', 'after')], default=None, max_length=6)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('title_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.title')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeRoom',
            fields=[
                ('employee_room_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.employee')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
            ],
            options={
                'db_table': 'employee_room',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='titles',
            field=models.ManyToManyField(related_name='titles', through='api.EmployeeTitle', to='api.title'),
        ),
    ]
