# Generated by Django 4.0.3 on 2022-04-18 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_title_remove_employee_room_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeetitle',
            table='employee_title',
        ),
        migrations.AlterModelTable(
            name='title',
            table='title',
        ),
    ]
