# Generated by Django 4.0.3 on 2022-04-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_employee_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='teachers',
            field=models.ManyToManyField(related_name='teachers', through='api.EmployeeRoom', to='api.employee'),
        ),
    ]
