FROM node:14.17.0-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH
COPY package.json ./
COPY package-lock.json ./
RUN npm ci --silent

COPY . ./

RUN npm run build

COPY ./build /var/www/html/