version: '3.7'

services:
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend:/usr/src/app
        ports:
            - "8000:8000"
    frontend:
        build: ./frontend
        ports:
            - "3000:3000"
        environment:
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - ./frontend:/usr/src/app
        command: npm start run